// wire-rs: encrypted protocol between Ark and host
// Copyright 2026 Dark Bio AG. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//! Generator of the protocol's protobuf bindings and message conversions.

use prost_types::field_descriptor_proto::Type;
use std::collections::BTreeSet;
use std::fmt::Write;
use std::fs;
use std::path::Path;

/// Generates the protobuf bindings and the schema-derived message and direction
/// conversions into the crate's source tree.
///
/// Checking the output into the source tree lets consumers build without protoc.
fn main() {
    // The schema and the generated sources live in the crate above this one
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("crate root");
    let proto = root.join("proto");
    let out_dir = root.join("src/protocol/generated");
    fs::create_dir_all(&out_dir).expect("create generated directory");

    // Use vendored protoc so no system dependency is needed
    let protoc = protoc_bin_vendored::protoc_bin_path().expect("vendored protoc");

    // Load the schema's descriptors, which the bindings are generated from last
    let mut config = prost_build::Config::new();
    config.protoc_executable(&protoc).out_dir(&out_dir);
    let descriptors = config
        .load_fds(&[proto.join("wire.proto")], &[&proto])
        .expect("failed to load wire.proto");

    // Collect the union of both envelopes' bodies with their schema field
    // names, for the public message enum. A body appears once even if it
    // travels both ways, such as develop bytes.
    let mut messages = BTreeSet::new();
    let mut conversions = String::new();
    let mut envelope_names = String::from("// This file is @generated by generator/src/main.rs.\n");
    for message in descriptors.file.iter().flat_map(|file| &file.message_type) {
        if !matches!(message.name(), "HostToArk" | "ArkToHost") {
            continue;
        }

        // Locate the envelope's content oneof and its generated module
        let oneof = message
            .oneof_decl
            .iter()
            .position(|oneof| oneof.name() == "content")
            .expect("envelope content oneof");
        let module = match message.name() {
            "HostToArk" => "host_to_ark",
            "ArkToHost" => "ark_to_host",
            _ => unreachable!(),
        };

        // Open the envelope's direction conversions and its field name lookup,
        // which names payloads in log lines without inspecting their bytes
        writeln!(conversions, "contents! {{ {module},").unwrap();
        writeln!(
            envelope_names,
            "impl opaque::{module}::Content {{\n    fn name(&self) -> &'static str {{\n        match self {{"
        )
        .unwrap();
        for field in &message.field {
            // The reader distinguishes unknown content from the envelope's own
            // fields by their tag range, so the layout is enforced here
            let content = field.oneof_index == Some(oneof as i32);
            assert_eq!(
                field.number() >= 0x100,
                content,
                "field {} breaks the envelope tag layout",
                field.name()
            );
            if !content {
                continue;
            }

            // Full body names distinguish requests and responses even when their
            // two wire envelopes use the same content field name and tag
            let (variant, payload) = match field.type_name.as_deref() {
                Some(name) => {
                    let name = name.rsplit('.').next().expect("protobuf message name");
                    (name, name)
                }
                None => {
                    assert_eq!(field.r#type().as_str_name(), "TYPE_BYTES");
                    assert_eq!(field.name(), "develop");
                    ("Develop", "Vec<u8>")
                }
            };
            messages.insert((variant, payload, field.name()));

            // Map the field's oneof variant, named in CamelCase like the generated
            // bindings, to its body and to its schema field name
            let field_variant: String = field
                .name()
                .split('_')
                .map(|word| {
                    let mut chars = word.chars();
                    chars
                        .next()
                        .expect("nonempty schema identifier")
                        .to_uppercase()
                        .collect::<String>()
                        + chars.as_str()
                })
                .collect();
            writeln!(conversions, "    {field_variant} => {variant},").unwrap();
            writeln!(
                envelope_names,
                "            Self::{field_variant}(..) => {:?},",
                field.name()
            )
            .unwrap();
        }

        // Close the envelope's direction conversions and field name lookup
        writeln!(conversions, "}}").unwrap();
        writeln!(envelope_names, "        }}\n    }}\n}}").unwrap();
    }

    // Write the message enum, followed by both envelopes' direction conversions
    let mut content =
        String::from("// This file is @generated by generator/src/main.rs.\nmessages! {\n");
    for (variant, payload, _) in &messages {
        writeln!(content, "    {variant}({payload}),").unwrap();
    }
    writeln!(content, "}}").unwrap();
    content.push_str(&conversions);

    // Name bodies by their schema field in log lines, matching the names the
    // envelope reader logs for received messages
    writeln!(
        content,
        "impl Message {{\n    /// Returns the payload's protobuf field name for log lines.\n    pub(super) fn field_name(&self) -> &'static str {{\n        match self {{"
    )
    .unwrap();
    for (variant, _, name) in &messages {
        writeln!(content, "            Self::{variant}(..) => {name:?},").unwrap();
    }
    writeln!(content, "        }}\n    }}\n}}").unwrap();

    // Write both generated sources into the crate
    fs::write(out_dir.join("message.rs"), content).expect("write message enum and conversions");
    fs::write(out_dir.join("darkbio.wire.names.rs"), envelope_names)
        .expect("write envelope field names");

    // Generate a second view of the envelopes with nested messages left as bytes.
    // Field numbers, oneofs and optional presence stay the same. The reader uses
    // this view for routing. Full decoding uses the original envelope bytes so
    // repeated message fields still merge as protobuf expects.
    let mut opaque = descriptors.clone();
    for file in &mut opaque.file {
        file.package = Some("darkbio.wire.opaque".into());
        file.enum_type.clear();
        file.message_type
            .retain(|message| matches!(message.name(), "HostToArk" | "ArkToHost"));
        for message in &mut file.message_type {
            for field in &mut message.field {
                if field.r#type() == Type::Message {
                    field.r#type = Some(Type::Bytes as i32);
                    field.type_name = None;
                }
            }
        }
    }
    let mut opaque_config = prost_build::Config::new();
    opaque_config.out_dir(&out_dir).bytes(["."]);
    opaque_config
        .compile_fds(opaque)
        .expect("generate opaque envelope views");

    // Generate the full bindings from the original descriptors
    config
        .compile_fds(descriptors)
        .expect("failed to compile wire.proto");
}
